In [1]:
import numpy as np

## NumPy arrays

Creating arrays

* `np.zeros`
* `np.ones`
* `np.full`
* `np.repeat`
* `np.array`
* `np.arange`

In [2]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
array = np.full(10, 1)
array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [7]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

Accessing the element of an array by index:

In [8]:
el = array[1]
print(el)

0.0


Accessing multiple elements of an array by a list of indices:

In [9]:
array = np.array([1,2,3,4,5,6,7])

In [10]:
array[[4, 2, 0]]

array([5, 3, 1])

Assignment:

In [11]:
array[1] = 1
print(array)

[1 1 3 4 5 6 7]


Creating an array from a list with integers:

In [12]:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

Specifying the type of elements:

In [13]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

`np.arange` for creating ranges:

In [14]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [15]:
#Also you could mention start stop for arange()

for i in np.arange(start=1, stop=5):
    print(i)

1
2
3
4


Linspace - for creating an array with elements from `start` till `end` of a certain size: 

In [16]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Be careful with overflowing:

In [17]:
zeros[0] = 300
zeros

array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [18]:
zeros[0] = 300
print(zeros[0])

44


In [19]:
300 % 256

44

## Multi-dimensional NumPy arrays

Specify the shape with a tuple:

In [20]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [21]:
print(zeros.shape)

(5, 2)


In [22]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [23]:
print(numbers[0, 1])

2


In [24]:
#also can we use double bracket
print(numbers[0][1])

2


Assignment: use a tuple (row index, column index)

In [25]:
numbers[0, 1] = 10

In [26]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
numbers[0]

array([ 1, 10,  3])

Slicing: getting a column:

In [28]:
numbers[:, 1]

array([10,  5,  8])

Assigning a row:

In [29]:
numbers[1] = [1, 1, 1]

In [30]:
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

Assigning a column:

In [31]:
numbers[:, 2] = [9, 9, 9]

In [32]:
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

In [33]:
# Accessing mutiple index in 2d array
numbers[[0,1,2], [0,1,2]]

array([1, 1, 9])

## Randomly generated arrays


Uniform random numbers between 0 and 1 of shape (5, 2):

In [34]:
np.random.rand(5, 2)

array([[0.08473468, 0.03732783],
       [0.52343304, 0.70326264],
       [0.40199151, 0.92631481],
       [0.39477308, 0.28078725],
       [0.8977485 , 0.17276739]])

Set seed for reproducibility:

In [35]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Random integers between 0 and 99 (100 is not included)

In [37]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [38]:
#You can also access the multiple element in 2d or more dimension array 

array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array[[0,1],[0,1],[0,1]] # [x...], [y...], [z...]

array([1, 8])

In [39]:
# 1. create array of size 10 with no 3 
# np.full(10,3)

# 2. create array of size 10,3 with 3 
# np.full((10,3),3)

# 3. Create an int array with normal disturbtion between 1 to 1000 of dimension 5*7
# np.random.seed(1)
# np.random.randint(size=(5,7), low=1, high=1000)

## Element-wise operations

In [40]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

Every item in the array is multiplied by 2:

In [41]:
rng * 2

array([0, 2, 4, 6, 8])

In [42]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

Adding one array with another

In [43]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [44]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [45]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

Rounding the numbers to 4th digit:

In [46]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

Two ways to square each element:

* element-wise multiplication with itself
* the power operator (`**`)

In [47]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [48]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [49]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

Other element-wise operations:

- `exp`
- `log`
- `sqrt`

In [50]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [51]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [52]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

### Comparison operations

In [53]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [54]:
result = pred >= 0.5
result

array([False, False,  True])

In [55]:
np.random.seed(2)

In [56]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [57]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [58]:
pred1 >= pred2

array([ True, False,  True])

In [59]:
np.random.seed(2)

In [60]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [61]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

### Logical operations

In [62]:
pred1 & pred2

array([ True, False, False])

In [63]:
pred1 | pred2

array([ True,  True,  True])

## Summarizing operations

Summarizing operations process and array and return a single number 

In [64]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [65]:
pred_sum

1.02

In [66]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


For two-dimentional array it works in the same way:

In [67]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [68]:
matrix.max()

0.62

But we can specify the axis along which we apply the summarizing operation

- `axis=1` - apply to each rows
- `axis=0` - apply to each column

In [69]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [70]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [71]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

## Sorting

In [72]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

Creaters a new array:

In [73]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [74]:
pred

array([0.44, 0.03, 0.55, 0.44])

Sorts in place:

In [75]:
pred.sort()

In [76]:
pred

array([0.03, 0.44, 0.44, 0.55])

Argsort - instead of sorting, return the indexes of the array in sorted order

In [77]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [78]:
idx = pred.argsort()

In [79]:
idx

array([1, 0, 3, 2])

In [80]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [81]:
#Let's try Argsort on 2d array 
# So for more dimension you could choose to sort along any axis default is axis=1(row)

array2d = np.random.randn(3,4).round(2)
print(array2d)
sortedindex = array2d.argsort(axis = 1)
print(array2d.argsort())
print(sortedindex)
print(np.take_along_axis(array2d, sortedindex, axis=1))
np.sort(array2d)
# array2d.take_along_axis(sortedinddex, axis=1)

[[-1.79 -0.84  0.5  -1.25]
 [-1.06 -0.91  0.55  2.29]
 [ 0.04 -1.12  0.54 -0.6 ]]
[[0 3 1 2]
 [0 1 2 3]
 [1 3 0 2]]
[[0 3 1 2]
 [0 1 2 3]
 [1 3 0 2]]
[[-1.79 -1.25 -0.84  0.5 ]
 [-1.06 -0.91  0.55  2.29]
 [-1.12 -0.6   0.04  0.54]]


array([[-1.79, -1.25, -0.84,  0.5 ],
       [-1.06, -0.91,  0.55,  2.29],
       [-1.12, -0.6 ,  0.04,  0.54]])

## Reshaping

The shape of an array cound be changed

In [82]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
rng.shape

(12,)

In [84]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

But number of rows x columns should be equal to the total number of elements

In [86]:
# rng.reshape(4, 4)

In [87]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [88]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

Putting mulitple arrays together:

- `concatenate`
- `hstack`
- `vstack`
- `column_stack`

In [89]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [90]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [91]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [92]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [93]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [94]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [95]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [96]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

Transpose

In [97]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [98]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

## Slicing

Taking a part of the array

In [99]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [100]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [102]:
mat[:, 2:3]

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [103]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [104]:
mat[[3, 0, 1]] # accessing multiple rows at once

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [105]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [106]:
mat[mat[:, 0] % 2 == 1] #getting rows for which the internal index is passes as true

array([[ 3,  4,  5],
       [ 9, 10, 11]])

## Linear Algebra
### Multiplication

Vector-vector multiplication

In [107]:
u = np.array([0, 1, 2])
v = np.array([1, 2, 3])

u.dot(v)

8

Matrix-vector multiplication

In [108]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [109]:
X.dot(u)

array([5, 8, 9])

In [110]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])

In [111]:
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

### Inverse

To inverse a matrix, use `inv` function from `linalg` package

In [112]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [113]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [114]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

B is not invertible ("singular"):

In [115]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

# np.linalg.inv(B)

Note: When you need to solve _Ax = b_, you don't really to compute the inverse. You can use `solve`:

In [116]:
b = np.array([1, 2, 3])

In [117]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [118]:
A.dot(x)

array([1., 2., 3.])