In [2]:
import numpy as np 

In [3]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition 
u + v

# subtraction 
u - v

# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [16]:
#Vector-vector multiplication

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    result = 0 
    size = u.shape[0]
    for i in range(size):
        result += u[i] * v[i]
    return result
        

In [11]:
def vector_vector_multiplication_(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [17]:
vector_vector_multiplication(u,v) == vector_vector_multiplication_(u,v)

True

In [40]:
#Matrix-vector multiplication

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    size = U.shape[0]
    result = np.ones(size)
    for i in range(size):
        result[i] = vector_vector_multiplication(U[i], v)
    return result
        

In [39]:
U= np.random.rand(4,4).round(2)
U

array([[0.34, 0.45, 0.23, 0.19],
       [0.86, 0.89, 0.36, 0.29],
       [0.9 , 0.01, 0.2 , 0.39],
       [0.23, 0.12, 0.95, 0.21]])

In [41]:
# og implementation
def matrix_vector_multiplication_(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [45]:
matrix_vector_multiplication_(U,v) == matrix_vector_multiplication(U,v)

array([ True,  True,  True,  True])

In [47]:
## matrix matrix multiplication

def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    size = V.shape[1]
    result = np.ones(U.shape[0], V.shape[1])
    
    for i in range(shape):
        result[:, i] = matrix_vector_multiplication(U, V[:, i])
    
    return result

In [49]:
V  = np.random.randint(low=10, high=100, size=(4,4))

In [50]:
V

array([[15, 72, 91, 68],
       [15, 16, 15, 21],
       [35, 55, 61, 50],
       [22, 98, 57, 64]])

In [52]:
def matrix_matrix_multiplication_(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [54]:
matrix_matrix_multiplication(U,V)

array([[ 24.08,  62.95,  62.55,  56.23],
       [ 45.23, 124.38, 130.1 , 113.73],
       [ 29.23, 114.18, 116.48,  96.37],
       [ 43.12,  91.31,  92.65,  79.1 ]])

In [55]:
matrix_matrix_multiplication_(U,V)

array([[ 24.08,  62.95,  62.55,  56.23],
       [ 45.23, 124.38, 130.1 , 113.73],
       [ 29.23, 114.18, 116.48,  96.37],
       [ 43.12,  91.31,  92.65,  79.1 ]])