In [1]:
import numpy as np

In [2]:
zeros = np.zeros(10)

In [3]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
tens = np.repeat(10, 5)
tens

array([10, 10, 10, 10, 10])

In [7]:
repeat = np.repeat([1,2,3], 3)
repeat 

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [8]:
repeat_more = np.repeat([1,2,3], [2,3,2])
repeat_more

array([1, 1, 2, 2, 2, 3, 3])

This is interesting way to access multiple cols

In [10]:
print(repeat_more[[1,2,0]])

[1 2 1]


In [12]:
array = [1,2,3,4,5]
numpy_array = np.array(array)
numpy_array

array([1, 2, 3, 4, 5])

In [13]:
type(numpy_array)

numpy.ndarray

In [14]:
arange = np.arange(11)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
linspace = np.linspace(0,1,11)
linspace

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
zeros = np.zeros(10, dtype="uint8")
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [21]:
zeros = np.zeros((3,2), dtype="int8")
zeros

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [7]:
random = np.full((3,2), 293, dtype="float64")
random

array([[293., 293.],
       [293., 293.],
       [293., 293.]])

In [8]:
random.shape

(3, 2)

In [10]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np_number = np.array(numbers)
np_number

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np_number[0,0]

1

In [13]:
np_number[:, 2]

array([3, 6, 9])

In [14]:
np_number[2, :]

array([7, 8, 9])

In [16]:
np_number[0] = [7,8,9]
np_number

array([[7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np_number[:, 2] = [1,2,3]
np_number

array([[7, 8, 1],
       [4, 5, 2],
       [7, 8, 3]])

Random array 

In [33]:
np.random.seed(5)
random = np.random.rand(5,2)
random

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [35]:
random = np.random.randn(5,2)
random

array([[-1.51117956,  0.64484751],
       [-0.98060789, -0.85685315],
       [-0.87187918, -0.42250793],
       [ 0.99643983,  0.71242127],
       [ 0.05914424, -0.36331088]])

In [37]:
# generate a random int between 10 and 100(exclusive) with sizze 10,3

random = np.random.randint(low=10, high=100, size=(10,3))
random


array([[21, 77, 75],
       [65, 13, 88],
       [37, 39, 43],
       [99, 95, 17],
       [26, 24, 41],
       [19, 48, 57],
       [26, 15, 44],
       [55, 69, 34],
       [23, 41, 42],
       [86, 54, 15]])

In [39]:
#shuffle the array 
idx = np.arange(5)
print('before shuffle', idx)
np.random.shuffle(idx)
print('after shuffle', idx)

before shuffle [0 1 2 3 4]
after shuffle [3 1 4 0 2]


In [40]:
#so numpy array are vectorized, means arithemtic applies to all 
arr = np.arange(5)
arr*2
arr

array([0, 1, 2, 3, 4])

It's also possible to have do the operation on two arrays if they have, same shape

In [41]:
noise = 0.01 * np.random.rand(5)
numbers = np.arange(5)

In [42]:
result = noise + numbers
result

array([3.77274637e-03, 1.00383903e+00, 2.00302002e+00, 3.00195131e+00,
       4.00736315e+00])

In [43]:
result.round(4)

array([3.8000e-03, 1.0038e+00, 2.0030e+00, 3.0020e+00, 4.0074e+00])

In [46]:
pred = np.random.rand(3).round(2)
pred = pred * pred
pred

array([0.7056, 0.7225, 0.4096])

In [48]:
pred_exp = np.exp(pred) # exponent
pred_exp

array([2.02506136, 2.05957572, 1.50621518])

In [50]:
pred_exp = np.log(pred)
pred_exp

array([-0.34870677, -0.32503786, -0.89257421])

In [52]:
pred_exp = np.sqrt(pred)
pred_exp

array([0.84, 0.85, 0.64])

Boolean expression could also be applied to the array

In [53]:
pred = np.random.rand(5).round(2)
pred

array([0.13, 0.18, 0.32, 0.96, 0.23])

In [54]:
output = pred > .4
output

array([False, False, False,  True, False])

In [56]:
pred1 = np.random.randn(10).round(3)
pred2 = np.random.rand(10).round(3)
print(pred1)
print(pred2)

[ 0.185  2.611  0.371 -1.418  0.571  0.488  0.581 -0.424  0.413 -0.569]
[0.934 0.716 0.128 0.122 0.605 0.984 0.904 0.261 0.597 0.334]


In [57]:
output = pred1 >= pred2
output

array([False,  True,  True, False, False, False, False, False, False,
       False])

Summarizing Operations

In [58]:
pred = np.random.rand(3).round(2)
pred

array([0.45, 0.64, 0.34])

In [59]:
pred.sum()

1.4300000000000002

In [60]:
pred.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [61]:
pred.min()

0.34

In [62]:
pred.max()

0.64

In [64]:
pred.mean()

0.47666666666666674

In [65]:
pred.std()

0.1239175353029407

it’s also possible to apply these operations to rows or columns separately.

In [71]:
array = np.random.rand(5,5).round(2)
array

array([[0.1 , 0.34, 0.82, 0.92, 0.76],
       [0.88, 0.85, 0.17, 0.58, 0.35],
       [0.74, 0.03, 0.17, 0.13, 0.98],
       [0.93, 0.71, 0.94, 0.74, 0.38],
       [0.89, 0.58, 0.83, 0.1 , 0.12]])

In [72]:
maximum = array.max(axis=1)
maximum

array([0.92, 0.88, 0.98, 0.94, 0.89])

In [73]:
sum_col = array.sum(axis=0)
sum_col

array([3.54, 2.51, 2.93, 2.47, 2.59])

Sorting a numpy array 

In [83]:
pred = np.random.rand(4).round(2)
pred

array([0.7 , 0.9 , 0.76, 0.76])

In [84]:
print(np.sort(pred))
print(pred)

[0.7  0.76 0.76 0.9 ]
[0.7  0.9  0.76 0.76]


In [79]:
pred.sort()
print(pred)

[0.17 0.43 0.53 0.74]


In [85]:
pred.argsort()

array([0, 2, 3, 1])

Reshaping the numpy array

In [88]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
arr.shape

(12,)

In [91]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Combining two arrays together 

In [92]:
vec = np.arange(3)
mat = np.arange(6).reshape(3, 2)

In [96]:
print(vec)
print(mat)

[0 1 2]
[[0 1]
 [2 3]
 [4 5]]


In [95]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [97]:
np.hstack([vec,vec])

array([0, 1, 2, 0, 1, 2])

But there is difference in how hstack and concatenate works on two dimensional array

concatenate: takes one dimensional array and returns big one dimensional array

In [98]:
np.concatenate([mat,mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [111]:
hstack = np.hstack([mat, mat])
hstack

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [109]:
np.vstack([hstack, hstack])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [107]:
np.column_stack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [114]:
# vstack can also stack togehter stack and matricies

np.vstack([mat.T, vec])

array([[0, 2, 4],
       [1, 3, 5],
       [0, 1, 2]])